### ISSUE TITLE
Just Crash

### ISSUE THREAD

**Issue by MrSliTraP2716Lua** [Polarite/Budding-Polar#3]
[crash-2025-10-30_15.24.30-client.txt](https://github.com/user-attachments/files/23235656/crash-2025-10-30_15.24.30-client.txt)
Version: 1.0.2
MC Version: 1.7.10

**Comment by Polarite** [comment]
I am seeing you are using a more updated fork of forge 1.7.10, can you try running the official 1.7.10 version of forge? I have made and tested the mod to work with 10.13.4.1614 version of forge.

**Comment by Polarite** [comment]
Can you please give more information because so far I think the issue isnt related to my mod.

**Comment by Ashen-sysadmin** [comment]
Did this start crashing after you added the mod?

> cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/event/FMLInitializationEvent

If it's throwing these around, I'm wondering if your pack boots even without this mod. ASM conflicts maybe?

**Comment by MrSliTraP2716Lua** [comment]
It's not all right anymore, I don't remember the reason why it didn't work.

**Comment by MrSliTraP2716Lua** [comment]
And by the way, there are no conflicts yet on the build with 750+ mods

**Comment by Polarite** [comment]
Allrighty, if you remember the issue and think its caused by my mod please share fml logs/latest log with crash log as well please.

**Comment by MrSliTraP2716Lua** [comment]
Okay, I'll try, but it seems to me the problem was too trivial. At first, the mod wasn't recognized by Forge at all.
